### PR TITLE
Couple of stylization fixes in MicroProfile bom

### PR DESCRIPTION
**Pull request by rhusar**

### CODE REVIEW

**Comment by kabir** [comment]
This is ok to test

**Comment by rhusar** [comment]
Looks like the whitelist is off on this repo..

**Comment by rhusar** [comment]
Anyway, the tests fail everywhere at the moment. Perhaps @emmartins forgot to push something somewhere?

**Comment by emmartins** [comment]
@rhusar the BOM version was wrong

**Comment by emmartins** [comment]
@rhusar btw can you please send a PR for 19.0.x branch too?

**Comment by rhusar** [comment]
>@rhusar the BOM version at master was wrong :-)

Cool thanks

> @rhusar btw can you please send a PR for 19.0.x branch too?

Sure, no problem - https://github.com/wildfly/boms/pull/85

**Pull request merged**
