### PR TITLE
Updated arquillian-core to 1.1.11.Final and SW Resolver to 2.2.2

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by ctomc** [comment]
I am bit afraid of upgrading arquillian, it is always a surprise what happens.

**Comment by MatousJobanek** [comment]
Yes, I believe so... The only a little bit annoying thing is a new warning https://issues.jboss.org/browse/ARQ-2012 This will be removed in the next version.
You can always downgrade it if you don't like it ;-)

**Comment by ctomc** [comment]
For boms I think it should be fine, upgrading it in WildFly will be bigger task.

**Comment by MatousJobanek** [comment]
Do you mean this one: https://github.com/wildfly/wildfly-arquillian/blob/master/pom.xml#L46? I just wanted to sent a PR :-D.
I have one more question - Why you haven't released the BOMs for the version 9.0.2.Final? I'm asking because I noticed that there are old versions of arquillian and some guys instead of using this BOM use the wildfly-parent as a BOM.

**Comment by ctomc** [comment]
Yeah that one :) you should send PR, but it will be take more time to get it merged for sure.

There was noting in WildFly 9.0.2 comparing to 9.0.1 that would merit new release of boms.
In boms we have mostly have versions of API dependencies, which usually don't change after .Final
Only real change in WF 9.0.2 was security patch.
It there would be bom 9.0.2 it would be identical to 9.0.1. 
I can do that if it will help people not be confused about it.

**Comment by MatousJobanek** [comment]
Yes, I though that this was the reason. If it is not a complication for you, please release it - the usage will be more intuitive.

**Pull request merged**
