### PR TITLE
9.x branch - updated arquillian-core to 1.1.11.Final and SW resolver to 2.2.2

### PR DESCRIPTION
**Pull request by MatousJobanek**

### CODE REVIEW

**Comment by ctomc** [comment]
this would give a reason for 9.0.2 :)

**Comment by MatousJobanek** [comment]
:-) Thanks

**Comment by ctomc** [comment]
9.0.2.Final was just released, 
sorry for the delay :|

**Comment by MatousJobanek** [comment]
Cool, thanks for the release  :+1:

**Pull request merged**
