### PR TITLE
move server dep version to snapshot, since current BOMs are no longer…

### PR DESCRIPTION
**Pull request by emmartins**
… compatible with 27.x

### CODE REVIEW

**Comment by emmartins** [comment]
@bstansberry this change is required to now build locally the BOMs without any sources modifications (requires pre-build of wildfly main tho, as noted in the comment above the changed version).

I don't really like to require the server building but think it's better to force it until we release WFLY 28 Beta, cause the changes recently committed on BOMs (which were also required to fix some QS), are not compatible with WildFly's server dep 27.x... WDYT?  

PS: It's expected that the BUILD DEFAULT tests fail

**Comment by jamezp** [comment]
@emmartins We could use the scm plugin to build WildFly automatically before we build this so the SNAPSHOT dependency is available. Something like this maybe https://github.com/jamezp/boms/commit/65f418fda3aabe5247554799a273c4e08c47c0c5

**Comment by bstansberry** [comment]
@emmartins I like @jamezp 's suggestion, although instead of making that profile active by default I'd use a property so it can be turned off when someone building knows they have a suitable snapshot already built.

```
<property>!skip.wildfly.build</property>
```

The github actions could perhaps add a step to build main once and then run all the other bits with -Dskip.wildfly.build=true

**Comment by jamezp** [comment]
+1 to not activating by default. This needs to be tested a bit too as I didn't get to do full testing with it due to another issue coming up.

**Comment by emmartins** [comment]
@bstansberry well I am now on PTO till March 17th, so maybe we won't need it? 

FYI: WFLY 28 Beta BOMs are ready to release, and QS may be skipped if Beta goes out before I come back

**Pull request closed without merging**
