### PR TITLE
Fix CI configs

### PR DESCRIPTION
**Pull request by luck3y**

### CODE REVIEW

**Comment by luck3y** [comment]
@emmartins This should correct the CI errors.

**Comment by luck3y** [comment]
@emmartins I can't flag you as a review, but can you take a look?

**Comment by emmartins** [comment]
@luck3y is this needed for quickstarts too?
@kabir fyi, you may need to update your MP4 branches

**Comment by luck3y** [comment]
@emmartins Not sure, are those failing as well? I just randomly noticed this one when looking for soemthing else.

**Pull request merged**
