### PR TITLE
Add github actions CI

### PR DESCRIPTION
**Pull request by luck3y**

### CODE REVIEW

**Comment by luck3y** [comment]
@emmartins This is passing for me locally now. It builds and installs wildfly then boms, then runs the tests in parallel.

**Comment by emmartins** [comment]
@luck3y out of curiosity, will this deal with different branches and JDKs?

**Comment by luck3y** [comment]
@emmartins It'll use the AdoptOpenJDK JDKs, and you can set which versions here: https://github.com/wildfly/boms/pull/92/files#diff-e9f950f17198d3d5e3122a44230a09b9R66

Regarding branches, that depends on how you want it to work, do you generally commit to branches after they're made? If not we can just run it on master, if you do want it on branches, then we'll need to either add a parameter to the config or use the branchname to match the upstream wildlfy version -- either is pretty easy, just let me know how you want it to work.

**Comment by luck3y** [comment]
Note, since this is merged now, I'm doing to pause the other CI, it'll still be there for a while if we need to switch back to it for some reason.

**Comment by emmartins** [comment]
@luck3y in BOMs it's not frequent to have PRs on branches, but wrt Quickstarts it's a different story, and it depends on BOMs.

**Comment by luck3y** [comment]
I've opened https://github.com/wildfly/boms/pull/93 to only run CI on master, we can always revisit if this needs to be changed.

I'll be looking at quickstarts at some point to move, we can discuss those issues when that PR is up.

**Pull request merged**
