### PR TITLE
Using bom builder to produce the jms-client-bom

### PR DESCRIPTION
**Pull request by ehsavoie**

### CODE REVIEW

**Comment by kabir** [comment]
This is ok to test

**Comment by emmartins** [comment]
@luck3y think there is something wrong with CI for BOMs, can you please check it out?

**Comment by luck3y** [comment]
@emmartins Looking

**Comment by emmartins** [comment]
maybe it's just the snapshot dependency building

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by emmartins** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by luck3y** [comment]
retest this please

**Comment by emmartins** [comment]
replaced by https://github.com/wildfly/boms/pull/77

**Pull request closed without merging**
